---
- name: Verify AAP controller API root
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Query controller API root
      ansible.builtin.uri:
        url: "{{ controller_api_url}}"
        method: GET
        validate_certs: true
        status_code: 200
      register: api_root
      ignore_errors: true

    - name: Assert controller API root responded
      ansible.builtin.assert:
        that:
          - api_root.status == 200
        fail_msg: "AAP controller API root is not responding"
        success_msg: "AAP controller API root responded successfully"