---
- name: Run Ping Test
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Request Google
      ansible.builtin.uri:
        url: https://www.google.com
        method: GET
        status_code: 200
      register: google_response
      ignore_errors: true

    - name: Assert connectivity worked
      ansible.builtin.assert:
        that:
          - google_response.status == 200
        fail_msg: "Connection to Google failed"
        success_msg: "Connection to Google succeeded"